apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-springboot-app
  template:
    metadata:
      labels:
        app: k8s-springboot-app
    spec:
      containers:
        - name: ecomm-springboot
          image: panprak/ecommerce-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: k8s-springboot-app